'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WebUserControl3
    
    '''<summary>
    '''titleLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents titleLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pageNumberLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pageNumberLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''PreviousPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PreviousPage As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''NextPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NextPage As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''BooksList1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BooksList1 As Global.Rent_A_Book.BooksList
End Class
