'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SignUpPage
    
    '''<summary>
    '''SignUpLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SignUpLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''NameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NameLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''NameTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NameTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''EmailLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmailLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''EmailTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmailTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''PasswordLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PasswordLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''PasswordTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PasswordTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ReEnterPasswordLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReEnterPasswordLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ReEnterPasswordTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReEnterPasswordTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''SignUpButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SignUpButton As Global.System.Web.UI.WebControls.Button
End Class
